### ISSUE TITLE
Funkcja z zadania 3 nie przechodzi wszystkich testów

### ISSUE THREAD

**Issue by kwisnia** [korona-science/homework-kwisnia#1]
Funkcja do zadania 3 nie chce przejść wszystkich testów(z bodajże 7 możliwych dla tego zadania 4 są niezaliczone). Nie wiem skąd może pochodzić problem, gdyż funkcja zwraca poprawne wyniki dla podanych przykładów oraz funkcja jest poprawiona by zwracała wynik krajów z nowymi zakażeniami w danym dniu, zgodnie z zaleceniami.
Nie wiem czy to pomoże ale załączam kod testów jakie nie zostały ukończone pomyślnie
  =========================== short test summary info ============================
  FAILED 94d924d735efa610c6071d11028a2ea0.py::test_no_new_cases[day1-month1-year1-result1]
  FAILED 94d924d735efa610c6071d11028a2ea0.py::test_no_new_cases[day3-month3-year3-result3]
  FAILED 94d924d735efa610c6071d11028a2ea0.py::test_no_new_cases[day4-month4-year4-result4]
  FAILED 94d924d735efa610c6071d11028a2ea0.py::test_no_new_cases_default_year[day1-month1-result1]
  ========================= 4 failed, 13 passed in 0.52s =========================
@amanujlo

**Comment by RouNNdeL** [comment]
Użyj biblioteki do dat
